-- MySQL Script generated by MySQL Workbench
-- Sun Sep 29 23:03:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`model` ;

CREATE TABLE IF NOT EXISTS `mydb`.`model` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`exterior_color`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`exterior_color` ;

CREATE TABLE IF NOT EXISTS `mydb`.`exterior_color` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color_name` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lights`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`lights` ;

CREATE TABLE IF NOT EXISTS `mydb`.`lights` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(250) NOT NULL,
  `prize` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rims`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`rims` ;

CREATE TABLE IF NOT EXISTS `mydb`.`rims` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(250) NOT NULL,
  `prize` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`wheels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`wheels` ;

CREATE TABLE IF NOT EXISTS `mydb`.`wheels` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `model` VARCHAR(250) NOT NULL,
  `prize` INT NOT NULL,
  `rims_id` INT NOT NULL,
  PRIMARY KEY (`id`, `rims_id`),
  INDEX `fk_wheels_rims1_idx` (`rims_id` ASC) VISIBLE,
  CONSTRAINT `fk_wheels_rims1`
    FOREIGN KEY (`rims_id`)
    REFERENCES `mydb`.`rims` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plastic_finish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plastic_finish` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plastic_finish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `prize` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ledger_finish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ledger_finish` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ledger_finish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `prize` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`interior_finish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`interior_finish` ;

CREATE TABLE IF NOT EXISTS `mydb`.`interior_finish` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plastic_finish_id` INT NOT NULL,
  `ledger_finish_id` INT NOT NULL,
  PRIMARY KEY (`id`, `plastic_finish_id`, `ledger_finish_id`),
  INDEX `fk_interior_finish_plastic_finish1_idx` (`plastic_finish_id` ASC) VISIBLE,
  INDEX `fk_interior_finish_ledger_finish1_idx` (`ledger_finish_id` ASC) VISIBLE,
  CONSTRAINT `fk_interior_finish_plastic_finish1`
    FOREIGN KEY (`plastic_finish_id`)
    REFERENCES `mydb`.`plastic_finish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_interior_finish_ledger_finish1`
    FOREIGN KEY (`ledger_finish_id`)
    REFERENCES `mydb`.`ledger_finish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`car` ;

CREATE TABLE IF NOT EXISTS `mydb`.`car` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prize` INT NOT NULL,
  `production_date` DATE NULL,
  `model_id` INT NOT NULL,
  `color_id` INT NOT NULL,
  `lights_id` INT NOT NULL,
  `wheels_id` INT NOT NULL,
  `wheels_rims_id` INT NOT NULL,
  `interior_finish_id` INT NOT NULL,
  PRIMARY KEY (`id`, `model_id`, `color_id`, `lights_id`, `wheels_id`, `wheels_rims_id`, `interior_finish_id`),
  INDEX `fk_car_model1_idx` (`model_id` ASC) VISIBLE,
  INDEX `fk_car_color1_idx` (`color_id` ASC) VISIBLE,
  INDEX `fk_car_lights1_idx` (`lights_id` ASC) VISIBLE,
  INDEX `fk_car_wheels1_idx` (`wheels_id` ASC, `wheels_rims_id` ASC) VISIBLE,
  INDEX `fk_car_interior_finish1_idx` (`interior_finish_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_model1`
    FOREIGN KEY (`model_id`)
    REFERENCES `mydb`.`model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_color1`
    FOREIGN KEY (`color_id`)
    REFERENCES `mydb`.`exterior_color` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_lights1`
    FOREIGN KEY (`lights_id`)
    REFERENCES `mydb`.`lights` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_wheels1`
    FOREIGN KEY (`wheels_id` , `wheels_rims_id`)
    REFERENCES `mydb`.`wheels` (`id` , `rims_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_car_interior_finish1`
    FOREIGN KEY (`interior_finish_id`)
    REFERENCES `mydb`.`interior_finish` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `surname` VARCHAR(250) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id` INT NOT NULL,
  `phone_number` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_client_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cost_center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cost_center` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cost_center` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(250) NOT NULL,
  `city` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dealer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_active` TINYINT(1) NULL,
  `cost_center_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`, `user_id`),
  INDEX `fk_dealer_cost_center1_idx` (`cost_center_id` ASC) VISIBLE,
  INDEX `fk_dealer_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_dealer_cost_center1`
    FOREIGN KEY (`cost_center_id`)
    REFERENCES `mydb`.`cost_center` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dealer_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `car_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `dealer_id` INT NOT NULL,
  `order_date` DATE NOT NULL,
  PRIMARY KEY (`id`, `car_id`, `client_id`, `dealer_id`),
  INDEX `fk_order_car1_idx` (`car_id` ASC) VISIBLE,
  INDEX `fk_order_client1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_order_dealer1_idx` (`dealer_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_car1`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`car` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_dealer1`
    FOREIGN KEY (`dealer_id`)
    REFERENCES `mydb`.`dealer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
